name: Allow only PRs from quality-assurance to main

on:
  pull_request:
    branches:
      - main

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check if source branch is quality-assurance
        run: |
          echo "Checking source branch..."
          echo "Source branch is: ${{ github.head_ref }}"
          if [ "${{ github.head_ref }}" != "quality-assurance" ]; then
            echo "ERROR: Only PRs from 'quality-assurance' branch are allowed into 'main'."
            exit 1
          fi
        shell: bash
